Telyt/Telyt/urls.py
"""Telyt URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
# Django imports
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # projects urls
    url(r'^', include('projects.urls', namespace='projects')),

    #allauth urls
    url(r'^accounts/', include('allauth.urls')),

    # provide the most basic login/logout functionality
    # url(r'^login/$', auth_views.LoginView.as_view(template_name='core/login.html'),
    #     name='core_login'),
    # url(r'^logout/$', auth_views.LogoutView.as_view(), name='core_logout'),

    # enable the admin interface
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Telyt/projects/urls.py
# Django imports
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from projects import views

app_name = 'projects'
urlpatterns = [
    # 
    url(r'^$',views.index,name="index"),
    url(r'^index/',views.index,name="index"),
    url(r'^dashboard/',views.dashboard,name="dashboard"),
    url(r'^addProjectPermission/',views.AddProjectPermission,name="addProjectPermission"),
    url(r'^projectdetails/(?P<projectid>[0-9]+)',views.project_details,name="projectdetails"),
    url(r'^projectdetailsedit/(?P<projectid>[0-9]+)',views.project_details_edit,name="projectdetailsedit"),
    url(r'^projectdetailsdelete/(?P<projectid>[0-9]+)',views.project_details_delete,name="projectdetailsdelete"),
    url(r'^projectadd/',views.project_create,name="projectadd"),
    url(r'^filesadd/(?P<projectid>[0-9]+)/$',views.file_upload,name="filesadd"),
    url(r'^filesdelete/(?P<fileid>[0-9]+)/(?P<projectid>[0-9]+)/$',views.file_delete,name="filesdelete"),
    url(r'^admindashboard/',views.admindashboard,name="admindashboard"),
    url(r'^userprojects/(?P<username>\w+)',views.user_projects,name="userprojects"),
    url(r'^adminprojectdetails/(?P<projectname>\w+)',views.adminproject_details,name="adminprojectdetails"),
    url(r'^profile/',views.profile,name="profile"),
    url(r'^profileupdate/(?P<userid>[0-9]+)/$',views.profile_update,name="profileupdate"),
    url(r'^profilepicture/(?P<userid>[0-9]+)/$',views.profile_picture,name="profilepicture"),
]

Telyt/templates/base.html
{% load static %}
<DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" media="screen" href="{% static 'style.css'%}">
    <title>{% block title %}Telyt Solutions{% endblock %}</title>
</head>
<body>
      
      <!-- Main navigation -->
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
          <div class="container">
            <!-- <a class="navbar-brand" href="#">
              <strong>Telyt Solutions</strong>
            </a>
            <a class="navbar-brand" href="#">
              <img src="/images/tely2.png" height="30px" alt="mdb logo"> -->
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7"
              aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto smooth-scroll">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'projects:index' %}">Home
                    <span class="sr-only">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#about" data-offset="90">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#services" data-offset="90">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#testimonials" data-offset="30">Testimonials</a>
                </li>
              </ul>
               <!-- buttons  -->
               <ul class="navbar-nav nav-flex-icons">
                {% if user.is_authenticated %}
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">
                            <button type="button" class="btn btn-primary waves-effect">log out</button>
                        </a>
                    </li> -->
                    <a class="collapse-item" href="#" data-toggle="modal" data-target="#logoutModal">
                      <button type="button" class="btn btn-primary waves-effect">Logout</button>
                    </a>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">
                            <button type="button" class="btn btn-primary waves-effect">Sign Up</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">
                        <button type="button" class="btn btn-primary waves-effect">Log in</button>
                        </a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <!-- Navbar -->     
      <!-- Main navigation -->
      {% block content %}base.html{% endblock %}

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
              </button>
              </div>
              <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
              <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <!-- <a class="btn btn-primary" href="{% url 'account_logout' %}">Logout</a> -->
              <form method="post" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  {% if redirect_field_value %}
                  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                  {% endif %}
                  <button type="submit" class="btn btn-primary">Log Out</button>
                </form>
              </div>
          </div>
          </div>
        </div>
        <!-- Footer -->
        <footer class="page-footer font-small" style="background-color: #2196F3;"> 

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2020 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/"> Devligence Limited</a>
        </div>
        <!-- Copyright -->
        <script src="{% static 'particles.js'%}"></script>
        <script src="{% static 'main.js'%}"></script>
            <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
        <script>
            $('.carousel').carousel({
            interval: 3000
        })
        </script>
        </footer>
        <!-- Footer -->
</body>
</html>